### ISSUE TITLE
Invalid `images.original.mp4` url

### ISSUE THREAD

**Issue by fedebertolini** [Giphy/GiphyAPI#112] opened 2017-01-22 12:11 UTC
Hi! I've found a Giphy that has an invalid `images.original.mp4` url. The giphy with id `3o7aTw0bSZ4wRr15g4` doesn't have the `.mp4` extension:

http://api.giphy.com/v1/gifs/3o7aTw0bSZ4wRr15g4?api_key=dc6zaTOxFJmzC

Result:
```
{
  "data":{
    "type":"gif",
    "id":"3o7aTw0bSZ4wRr15g4",
    "slug":"reaction-trippy-quentin-tarantino-3o7aTw0bSZ4wRr15g4",
    "url":"http:\/\/giphy.com\/gifs\/reaction-trippy-quentin-tarantino-3o7aTw0bSZ4wRr15g4",
    "bitly_gif_url":"http:\/\/gph.is\/2d7dJU6",
    "bitly_url":"http:\/\/gph.is\/2d7dJU6",
    "embed_url":"http:\/\/giphy.com\/embed\/3o7aTw0bSZ4wRr15g4",
    "username":"",
    "source":"",
    "rating":"g",
    "content_url":"",
    "source_tld":"",
    "source_post_url":"",
    "is_indexable":0,
    "import_datetime":"2016-09-27 19:16:49",
    "trending_datetime":"0000-00-00 00:00:00",
    "images":{
      ....
      "original":{
        "url":"http:\/\/media1.giphy.com\/media\/3o7aTw0bSZ4wRr15g4\/giphy.gif",
        "width":"480",
        "height":"204",
        "size":"1728066",
        "frames":"50",
        "mp4":"http:\/\/media1.giphy.com\/media\/3o7aTw0bSZ4wRr15g4\/giphy",
        "mp4_size":"68100",
        "webp":"http:\/\/media1.giphy.com\/media\/3o7aTw0bSZ4wRr15g4\/giphy.webp",
        "webp_size":"596960",
        "hash":"6529314a59cb6389010bcd1cdd56c2d5"
      },
      ....
    }
  },
  "meta":{
    "status":200,
    "msg":"OK",
    "response_id":"58849e215c8085044d5b410c"
  }
}
```

If you try to download the url returned by the api you get a 403 error: http://media1.giphy.com/media/3o7aTw0bSZ4wRr15g4/giphy

**Comment by nkhoshini** [comment] 2017-01-23 03:13
@fedebertolini Nice catch! We're looking into why this is occurring and will respond back when we have a fix in place.

Thanks for filing this 🥇

**Comment by dfinkler** [comment] 2017-06-14 18:54
looks like this GIF was re-coded and looks good now.  We have audited the import pipe line and confirmed that non-GIF renditions are looking good.  Closing the issue now as it should be resolved.

**Closed by dfinkler** 2017-06-14 18:54 UTC
Labels: bug
